# fly.toml app configuration file generated for ancient-voice-480 on 2023-08-25T12:24:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ancient-voice-480"
primary_region = "ewr"
console_command = "/code/manage.py shell"

[build]

[env]
  DJANGO_SETTINGS_MODULE = "wanderlust.settings"

[deploy]
  release_command = "poetry run python manage.py migrate"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
