# Generated by Django 4.2.2 on 2023-08-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_trips_accepted_users_triprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='country',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='country',
            field=models.CharField(default='', max_length=60),
        ),
    ]
